// ///////////////////////////
// Alexander Trefonas      //
// 7/9/2021                //
// Copyright Algodev Inc   //
// All Rights Reserved.    //
// ///////////////////////////

/**
 * @type {{LOCAL_ALGOD_SERVER: (string|string), PUBLIC_TEST_INDEXER_PORT: string, TEST_ASA_ORDERBOOK_APPID: number, PROD_ALGOD_SERVER: (T|string), PUBLIC_TEST_ALGOD_SERVER: (T|string), PUBLIC_TEST_BACKEND_API: string, PUBLIC_TEST_INDEXER_TOKEN: string, TEST_INDEXER_PORT: string, TEST_ALGOD_TOKEN: (T|string), TEST_INDEXER_TOKEN: string, PROD_ALGO_ORDERBOOK_APPID: number, PROD_INDEXER_PORT: string, TEST_ALGOD_SERVER: (T|string), LOCAL_ALGOD_TOKEN: (string|string), MIN_ASA_ESCROW_BALANCE: number, PUBLIC_TEST_ASA_ORDERBOOK_APPID: number, TEST_INDEXER_SERVER: string, LOCAL_ASA_ORDERBOOK_APPID: number, PROD_BACKEND_API: string, TEST_BACKEND_API: string, PUBLIC_TEST_INDEXER_SERVER: string, TEST_ALGO_ORDERBOOK_APPID: number, LOCAL_INDEXER_SERVER: string, PROD_INDEXER_TOKEN: string, LOCAL_ALGO_ORDERBOOK_APPID: number, LOCAL_BACKEND_API: string, PROD_ALGOD_TOKEN: (T|string), LOCAL_ALGOD_PORT: (string|string), LOCAL_INDEXER_TOKEN: string, DEBUG: number, PROD_ALGOD_PORT: (T|string), MIN_ESCROW_BALANCE: number, PROD_INDEXER_SERVER: string, ESCROW_CONTRACT_VERSION: number, DEBUG_SMART_CONTRACT_SOURCE: (number|number), TEST_ALGOD_PORT: (T|string), PUBLIC_TEST_ALGOD_TOKEN: (T|string), PROD_ASA_ORDERBOOK_APPID: number, LOCAL_INDEXER_PORT: string, PUBLIC_TEST_ALGOD_PORT: (T|string), INFO_SERVER: string, PUBLIC_TEST_ALGO_ORDERBOOK_APPID: number, ORDERBOOK_CONTRACT_VERSION: number}}
 */
module.exports = {
  ESCROW_CONTRACT_VERSION: 6,
  MIN_ESCROW_BALANCE: 500000,
  MIN_ASA_ESCROW_BALANCE: 500000,
  ALGO_ORDERBOOK_APPID: 354073718,
  ASA_ORDERBOOK_APPID: 354073834,
  TEST_ALGO_ORDERBOOK_APPID: 22045503,
  TEST_ASA_ORDERBOOK_APPID: 22045522,
};
